Register tournaments
TranscendenceEpicPong/backend-mypy pull request #16
Opened 2024-03-01 16:49 UTC by loichu

Tournois:
 - updated model
 - sécurité (pas pouvoir accéder à un tournois auquel on ne participe pas, rôle créateur)
 - unit tests
 - viewset (API routes)

routes des tournois:
 - `POST /tournaments/` Create tournament
 - `GET /tournaments/` List tournaments
 - `GET /tournaments/${id}` Retrieve tournament
 - `POST /tournaments/register` register to a tournament with an alias
 - `POST /tournaments/launch` (only for creator) Launch the tournament (pool phase)

2024-03-02 13:51 UTC, baku00 requested changes

2024-03-02 13:51 UTC, baku00 commented on backend/authentication/views.py
À moins que côté front se soit changer, en général je regarde le status et ensuite je récupère le message

2024-03-02 15:53 UTC, baku00 commented
Fais aussi attention parce que tu as supprimé le champs "max_participants" du model mais pas de la commande create tournament

2024-03-02 15:57 UTC, baku00 commented
Faut pas oublier admin.py

2024-03-04 18:06 UTC, loichu commented
> Fais aussi attention parce que tu as supprimé le champs "max_participants" du model mais pas de la commande create tournament

Normalement on en aura plus besoin quand on aura le front, de toute façon on pourra pas tester avec un tournois créé de cette manière

2024-03-04 18:17 UTC, loichu commented
> Faut pas oublier admin.py

Il a été supprimé ya longtemps, je l'ai remis et j'ai pas testé en profondeur mais ça a l'air ok. de toute façon pas sûr qu'on en ait encore besoin

2024-03-04 18:33 UTC, baku00 approved these changes

2024-03-04 18:33 UTC, baku00 approved these changes

2024-03-04 18:35 UTC, merged